apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: weather-service
build:
  artifacts:
    - image: gcr.io/aviralmansingka-pulumi-gke/weather-service
      jib: {}
deploy:
  kubectl:
    manifests:
      - manifests/*
